logging:
  file:
    path: logs
  level:
    root: info
    #    com.zaxxer.hikari.HikariConfig: DEBUG
    #    com.zaxxer.hikari: TRACE
    org.hibernate:
      #      SQL: DEBUG
      orm.jdbc.bind: TRACE
  logback:
    rollingpolicy:
      max-history: 7

spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  autoconfigure:
    excludd: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
    exclude:
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticsearchRestHealthContributorAutoConfiguration
  datasource:
#    url: jdbc:mariadb://localhost:3306/shoescms
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password:
    url: jdbc:mysql://mysql-shoes-bietcankhong-4a79.i.aivencloud.com:27469/shoescms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      validation-timeout: 10000
      maxLifetime: 1790000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate:
      default_batch_fetch_size: 100
      format_sql: true
      show_sql: true

    hibernate:
      ddl-auto: update

  messages:
    basename: i18n/exception
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  jwt:
    secret: VyAHb65Ww8V1vj2FXHMS6g==

  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 50MB
  config:
    import: optional:file:.env[.properties]
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-model-expand-depth: 99

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:

    credentials:
      access-key: COG9cbWGCwLg2h2iLmmOgaPMo5tU5yAN6k8JIZ/cfTw=
      secret-key: JcHJHjF3vuy1ZznEcc+IT3F1i2xT3QwkThF12PsIsu7Md7EYh0tWyyr8cXuWMJJ/

shoescms:
  vnpayredirect: https://shoes-user-nxd.netlify.app/dat-hang/ket-qua
  forgotPassword: https://shoes-user-nxd.netlify.app/quen-mat-khau

photoism:
  encrypt:
    key: Uyn+GjQZ1to6HCyxxnCv7yyY8OGI9uhTiVkWEPAqOz4=
  mail:
    chgpassurl: https://dev-cms.seobuk.kr/#/confirm-password
    smtp:
      host: smtp.gmail.com
      port: 587
      user: bietcankhong@gmail.com
      pass: 'kmmaizupandrxjae'
      auth: true
      starttls.enable: true


